# SPDX-FileCopyrightText: 2025 Adrien Dorsaz
# SPDX-License-Identifier: GPL-3.0-or-later

[[dictionaries]]
locales = ["de_AT", "de_CH", "de_DE"]
uris = [
  "/app/share/org.muttum.muttum/de_AT",
  "/app/share/org.muttum.muttum/de_CH",
  "/app/share/org.muttum.muttum/de_DE",
]
project_uri = "https://j3e.de/ispell/igerman98/"
repository_uri = "https://j3e.de/ispell/igerman98/dict/"
credits = [
  "Daniel NABER",
  "Werner LEMBERG",
  "László NÉMETH",
  "Jan SCHREIBER",
  "Roland ROSENFELD",
  "Till BERGER",
  "Franz Michael BAUMANN",
]
license = "GPL-3.0-only"
version = "20161207"
definition_url_template = "https://de.wiktionary.org/wiki/{}"
min_word_length = 5
max_word_length = 8
number_of_attempts = 6
alphabet = "latin"

[[dictionaries]]
locales = ["en_AU", "en_CA", "en_GB", "en_US"]
uris = [
  "/app/share/org.muttum.muttum/en_AU",
  "/app/share/org.muttum.muttum/en_CA",
  "/app/share/org.muttum.muttum/en_GB",
  "/app/share/org.muttum.muttum/en_US",
]
project_uri = "http://wordlist.aspell.net/"
repository_uri = "http://wordlist.aspell.net/"
credits = [
  "Kevin Atkinson <kevina@gnu.org>",
  "Alan Beale <biljir@pobox.com>",
]
license = "MIT-like"
version = "2020.12.07"
definition_url_template = "https://en.wiktionary.org/wiki/{}"
min_word_length = 5
max_word_length = 8
number_of_attempts = 6
alphabet = "latin"

[[dictionaries]]
locales = ["fr"]
uris = ["/app/share/org.muttum.muttum/fr"]
project_uri = "https://salsa.debian.org/gpernot/wfrench.git"
repository_uri = "https://salsa.debian.org/gpernot/wfrench.git"
credits = [
  "guillaume pernot <gpernot@praksys.org>",
  "Paul Leyland <pcl@ox.ac.uk>",
  "Nicolas Sabouret <nico@debian.org>",
  "Francois Marier <francois@debian.org>",
]
license = "GPL-3.0-or-later"
version = "trixie"
definition_url_template = "https://fr.wiktionary.org/wiki/{}"
min_word_length = 5
max_word_length = 8
number_of_attempts = 6
alphabet = "latin"
